module:
    hugoVersion:
        extended: true
        min: "0.87.0"
baseURL: http://localhost:1313/
title: REmpire
keywords: REmpire, клан империя, невер, неверфейт, сайт клана, neverfate
description: Сайт клана REmpire из игры Неверфейт.
paginate: 10
hasCJKLanguage: true
languageCode: 'en-us'
theme:
params:
  opengraph:

    twitter: 'https://twitter.com'
    facebook: 'https://facebook.com'
  footer:
    hidePowered: false
    since: 2020
    copyright: REmpire
  prefix:
    h2: ""
    h3: ""
menu:
  navs:
    - name: О клане
      params:
        img: /img/logo_s.png
      weight: 1
      url: /about_clan
      - name: Устав
      params:
        img: /img/logo_s.png
      url: /law.html
      weight: 2
      - name: Состав
      params:
        img: /img/logo_s.png
      url: /about
      weight: 3
    - name: Локации НФ
      params:
        img: /img/logo_s.png
      url: /projects/
      weight: 4
