module:
    hugoVersion:
        extended: true
        min: "0.87.0"
baseURL: http://localhost:1313/
title: Клан REmpire
keywords: REmpire
description: Сайт клана REmpire
paginate: 10
hasCJKLanguage: true
languageCode: 'en-us'
theme: # "hugo-theme-onelou"
params:
  opengraph:
    vk: 'https://vk.com'
    twitter: 'https://twitter.com'
    facebook: 'https://facebook.com'
  footer:
    hidePowered: false # Створено в Україні
    beian: # ICP备案号
    gongan:
      # code: 公安备案号XXXX
      # txt: 京公网安备XXXX号
    since: 2020
    copyright: Rempire
  prefix:
    h2: "※ "
    h3: "✧ "
menu:
  navs:
    - name: О клане
      params:
        img: /img/logo2.png
      weight: 2
      url: /about
    - name: Локации НФ
      params:
        img: /img/logo2.png
      url: /projects/
      weight: 4
    - name: Состав
      params:
        img: /img/logo3.png
      url: /about
      weight: 3
    - name: Устав
      params:
        img: /img/logo3.png
      url: /404.html
      weight: 2
