baseURL: http://localhost:1313/
title: OneLou
keywords: OneLou
description: OneLou
paginate: 10
hasCJKLanguage: true
languageCode: 'en-us'
theme: # "hugo-theme-onelou"
params:
  opengraph:
    github: 'https://github.com/jyygithub'
    gitee: 'https:://gitee.com/jiangyychn'
    csdn: 'https:://blog.csdn.net/jiangyychn'
    juejin: 'https://juejin.cn/user/1996368845219944'
    jianshu: 'https://www.jianshu.com/u/a8e69e7aeea8'
    twitter: 'https://twitter.com'
    facebook: 'https://facebook.com'
  footer:
    hidePowered: false # Powered by Hugo & theme OneLou
    beian: # ICP备案号
    gongan:
      # code: 公安备案号XXXX
      # txt: 京公网安备XXXX号
    since: 2022
    copyright: XXX
  prefix:
    h2: "※ "
    h3: "✧ "
menu:
  navs:
    - name: Note
      params:
        img: /img/logo1.png
      weight: 1
      url: /note/
    - name: Blog
      params:
        img: /img/logo2.png
      url: /post/
      weight: 2
    - name: About
      params:
        img: /img/logo3.png
      url: /404.html
      weight: 3
